### ISSUE TITLE
[next] protect health check endpoint against DDoS

### ISSUE THREAD

**Issue by tobkle** [nhost/hasura-backend-plus#175]
In which state is V2 at the moment? The docker container produces 404s always after a few minutes when I've used the route /auth/login at least once (which worked).

I'm trying to develop against the [V2 docker container ](https://hub.docker.com/layers/tobkle/hasura-backend-plus/v2/images/sha256-389e53542aeda4455c72936361d23b114e21238184a6ca0f94093d7541d62c76?context=repo) with even today's github code line. There is no error in the log. I've even decreased the time for the health checks to 2s and scaled the container to 4 parallel containers in the hope to be lucky with at least one working container. But all 4 parallel containers are getting unhealthy at the same time. The graphql-engine stays healthy and is answering requests. Running the containers behind traefik instead of caddy, but I don't think, that has anything to do with it. 

Anyone an idea what it could be?

**Comment by tobkle** [comment]
Now, I get a message in the container:

```
/app # wget localhost:3000/healthz 
Connecting to localhost:3000 (127.0.0.1:3000)
wget: server returned error: HTTP/1.1 429 Too Many Requests
```

Looks like something with the rate limits?

**Comment by elitan** [comment]
It looks indeed like its rate limits that are kicking in:
https://github.com/nhost/hasura-backend-plus/blob/v2/src/limiter.ts

@plmercereau and @pnfcre knows more about this and might give some insight.

Until they reply, what's your environment variables related to HBPv2? Might be helpful for debugging

**Comment by elitan** [comment]
I think we should make the rate limiter opt in.

**Comment by tobkle** [comment]
I know now what it is:
it is the rate limiter in combination with the healthcheck in the Dockerfile.
The healthcheck calls are also included in the ratelimit counter.

**Comment by elitan** [comment]
@tobkle Understood.  What would be the best option here you think? To make the `/healthz` endpoint outside the rate limiter?

**Comment by tobkle** [comment]
The rate limiter is a useful feature, but whether the default values for MAX_REQUESTS and TIME_FRAME have reasonable defaults, or the route /healthz should be outside the limit counter

**Comment by elitan** [comment]
Relevant if we want to skip `/healthz`: https://www.npmjs.com/package/express-rate-limit#skip

**Comment by plmercereau** [comment]
Are we 100% sure rate limiter is the problem? @tobkle could you try to set MAX_REQUESTS and TIME_FRAME to very high numbers to check if it solves the problem?
In parallel I will work on a fix to skip health check to the rate limiter

**Comment by tobkle** [comment]
OK, I try that

**Comment by tobkle** [comment]
adjusted my Dockerfile:
```
HEALTHCHECK --interval=2s --timeout=2s --retries=2 CMD wget localhost:${PORT}/healthz -q -O - > /dev/null 2>&1
```

adjusted my docker-compose.yaml:
```
...
MAX_REQUESTS: 999999
TIME_FRAME: 10
...
````
Did many rest calls with this environment variable against /auth/login, now the docker container stays healthy.

So I suppose that was the reason.

**Comment by tobkle** [comment]
Thansk a lot for the fast response on a Sunday :-)

**Comment by plmercereau** [comment]
Allright then! I'll whitelist the health check endpoint!
It's very good to get feedback, especially when it helps us to correct bugs, but please keep in mind v2 is not yet released, so you may not want to use it in production (yet!)
Best

**Comment by tobkle** [comment]
Does it make sense to somehow return a

```429 Too Many Requests```

instead of a ```404 Not found```?

**Comment by tobkle** [comment]
I don't use it in production. I'm in early dev stage, but I want to work with the most current environment.

**Comment by plmercereau** [comment]
yes it should return `429` already, and not `404`, hence my request to change the limiter config. I'll push a fix and hopefully it will solve the issue

**Comment by tobkle** [comment]
Thank you. Btw, this is a docker-compose.yml for a test environment. It is running behind a separate container with [traefik](https://docs.traefik.io/), which cares about reverse-proxying, load-balancing and letsencrypt-certificate loading/updating. Haven't tried caddy yet, which I suppose you are using.

```
version: '3.6'
services:

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: my-postgres-password
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - 'postgres'
    environment:
      PGADMIN_DEFAULT_EMAIL: my-pgadmin-user
      PGADMIN_DEFAULT_PASSWORD: my-pgadmin-password
    volumes:
    - ./pgadmin_files:/var/lib/pgadmin
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - proxy
    labels:
      - "traefik.frontend.rule=Host:admin.example.com"
      - "traefik.port=80"
      - "traefik.backend=hasura_admin"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.auth.basic=basic-auth-user:basic-auth-encrypted-password"

  graphql-engine:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: my-hasura-admin-secret
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:my-postgres-password@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
    volumes:
      - ./migrations:/hasura-migrations
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - internal
    - proxy
    labels:
    - "traefik.frontend.rule=Host:graphql.example.com"
    - "traefik.port=8080"
    - "traefik.backend=hasura_graphql"
    - "traefik.enable=true"
    - "traefik.docker.network=proxy"

  hasura-backend-plus:
    image: tobkle/hasura-backend-plus:v2
    restart: always
    depends_on:
      - 'graphql-engine'
      - 'minio'
    environment:
      MAX_REQUESTS: 999999
      TIME_FRAME: 10
      SERVER_URL: 'https://backendv2.example.com'
      AUTH_ACTIVE: 'true'
      AUTH_LOCAL_ACTIVE: 'true'
      AUTH_REGISTRATION_FIELDS: 'first_name, last_name'
      USER_REGISTRATION_AUTO_ACTIVE: 'false'
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: my-hasura-admin-secret
      S3_ACCESS_KEY_ID: s3-access-key-id
      S3_SECRET_ACCESS_KEY: s3-secret-access-key
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: s3-bucket
      REFRESH_TOKEN_EXPIRES: 43200
      JWT_TOKEN_EXPIRES: 15
      SMTP_ENABLE: 'true'
      SMTP_HOST: smtp.eu.mailgun.org
      SMTP_PORT: 465
      SMTP_USER: me@example.com
      SMTP_PASS: my-mailgun-password
      SMTP_SECURE: 'true'
      SMTP_SENDER: me@example.com
    volumes:
      - ./storage-rules:/app/src/storage/rules
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - internal
    - proxy
    labels:
    - "traefik.frontend.rule=Host:backendv2.example.com"
    - "traefik.port=3000"
    - "traefik.backend=hasura_backendv2"
    - "traefik.enable=true"
    - "traefik.docker.network=proxy"

  minio:
    image: minio/minio
    restart: always
    volumes:
      - 'minio_data:/data'
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      S3_BUCKET: s3-bucket
      MINIO_ACCESS_KEY: s3-access-key-id
      MINIO_SECRET_KEY: s3-secret-access-key
    entrypoint: sh
    command: "-c 'mkdir -p /export/$${S3_BUCKET} && /usr/bin/minio server /export'"
    networks:
    - internal
    - proxy
    labels:
    - "traefik.frontend.rule=Host:myfiles.example.com"
    - "traefik.port=9000"
    - "traefik.backend=myfiles"
    - "traefik.enable=true"
    - "traefik.docker.network=proxy"

volumes:
  db_data:
  minio_data:

networks:
    proxy:
        external: true
    internal:
        external: false
```
