### ISSUE TITLE
Support: Kubernetes support

### ISSUE THREAD

**Issue by ewhal** [nhost/hasura-backend-plus#241]
Could include a basic setup of postgres-ha, minio and kubernetes and/or helm packaging for hbp.

**Comment by aaronhayes** [comment]
@ewhal if you are using Pulumi and AWS EKS I've made a demo that deploys:
 - Hasura Instance
- Hasura Backend Plus
- Ingress (via Helm)
- RDS PostgreSQL

https://github.com/aaronhayes/pulumi-hasura-aws-eks-example

Could be a good starting point for others as well.

**Comment by Aervue** [comment]
Hey, you can use https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/#install_ways-0 to translate from docker-compose, I will also be uploading a 1 click install with garden.io (kubernetes orchestrator) in the following days

**Comment by MichaelJCole** [comment]
This can be a little tricky as Kubernetes ingress' are more complicated than docker compose.

Here's what I'm doing now.  Is it interesting for a PR?

1) Install Docker Desktop for Windows/Mac (or apply these notes to your configuration)
2) Turn on Kubernetes: Docker Desktop -> Settings -> Kubernetes -> Enable Kubernetes
3) Describe your architecture in a "kustomization.yaml" file.  
```
resources:
  - cert-manager.yaml
  - postgres.yaml
  - hasura.yaml
  - minio.yaml
  - hasura-backend-plus.yaml
  - www.yaml
  - ingress.yaml
```
4) Describe each individual service:

Cert-manager (used to issue https certs)
```
wget https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.yaml .
```

postgres.yaml (Postgres official image)
``` 
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: myapplication
    tier: postgres
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgrespassword"
  POSTGRES_DB: "postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: myapplication
    tier: postgres
spec:
  ports:
    - name: postgres-tcp
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: myapplication
    tier: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: myapplication
    tier: postgress
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: myapplication
      tier: postgres
  template:
    metadata:
      labels:
        app: myapplication
        tier: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgredb-dev
              mountPath: /var/lib/postgresql
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgredb-dev
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
```
hasura.yaml (Hasura official image):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-config
  labels:
    app: myapplication
    tier: hasura
data:
  HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:postgrespassword@postgres:5432/postgres"
  HASURA_GRAPHQL_ADMIN_SECRET: "HASURA_GRAPHQL_ADMIN_SECRET"
  HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus/auth/jwks"}'
  HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
  # Dev mode
  HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
  HASURA_GRAPHQL_DEV_MODE: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: hasura
  labels:
    app: myapplication
    tier: hasura
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: myapplication
    tier: hasura

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
  labels:
    app: myapplication
    tier: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapplication
      tier: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapplication
        tier: hasura
    spec:
      containers:
        - image: hasura/graphql-engine:v1.3.2
          imagePullPolicy: Always
          name: hasura
          envFrom:
            - configMapRef:
                name: hasura-config
          ports:
            - containerPort: 8080
              protocol: TCP
```
minio.yaml (Minio official image):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  labels:
    app: myapplication
    tier: minio
data:
  S3_BUCKET: "hasura-backend-plus"
  MINIO_ACCESS_KEY: "MINIO_ACCESS_KEY"
  MINIO_SECRET_KEY: "MINIO_SECRET_KEY"

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: myapplication
    tier: minio
spec:
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: myapplication
    tier: minio

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: myapplication
    tier: minio
spec:
  serviceName: "minio"
  replicas: 1
  selector:
    matchLabels:
      app: myapplication
      tier: minio
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapplication
        tier: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: minio-config
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: minio-dev
              mountPath: /data
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export",
            ]
  volumeClaimTemplates:
    - metadata:
        name: minio-dev
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
```
hasura-backend-plus.yaml (Hasura Backend Plus - change to official image):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-backend-plus-config
  labels:
    app: myapplication
    tier: hasura-backend-plus
data:
  HASURA_ENDPOINT: "http://hasura/v1/graphql"
  HASURA_GRAPHQL_ADMIN_SECRET: "HASURA_GRAPHQL_ADMIN_SECRET"
  AUTO_MIGRATE: "true"
  # Storage
  S3_ENDPOINT: "http://minio:9000"
  S3_BUCKET: "hasura-backend-plus"
  S3_ACCESS_KEY_ID: "MINIO_ACCESS_KEY"
  S3_SECRET_ACCESS_KEY: "MINIO_SECRET_KEY"
  # User Features
  JWT_ALGORITHM: "RS256"
  AUTO_ACTIVATE_NEW_USERS: "false"
  # Email features
  EMAILS_ENABLE: "true"
  VERIFY_EMAILS: "true"
  LOST_PASSWORD_ENABLE: "true"
  SERVER_URL: "https://www.myapplication.com/auth/"
  # SMTP configuration
  SMTP_ENABLE: "true"
  SMTP_SENDER: "myapplication@mail.myapplication.com"
  SMTP_HOST: "smtp.sparkpostmail.com"
  SMTP_PASS: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  SMTP_USER: "SMTP_Injection"
  SMTP_PORT: "587"
  #SMTP_SECURE: "false"   # will automatically upgrade with STARTTLS

---
apiVersion: v1
kind: Service
metadata:
  name: hasura-backend-plus
  labels:
    app: myapplication
    tier: hasura-backend-plus
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: myapplication
    tier: hasura-backend-plus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-backend-plus
  labels:
    app: myapplication
    tier: hasura-backend-plus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapplication
      tier: hasura-backend-plus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapplication
        tier: hasura-backend-plus
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - image: registry.gitlab.com/myapplication/hasura-backend-plus:latest
          name: hasura-backend-plus
          envFrom:
            - configMapRef:
                name: hasura-backend-plus-config
          ports:
            - containerPort: 3000
```
www.yaml (Your web app in your Docker image)
NOTE: include example with echo or similar public docker image
```
apiVersion: v1
kind: Service
metadata:
  name: www
  labels:
    app: myapplication
    tier: www
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapplication
    tier: www

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  labels:
    app: myapplication
    tier: www
spec:
  selector:
    matchLabels:
      app: myapplication
      tier: www
  replicas: 1
  template:
    metadata:
      labels:
        app: myapplication
        tier: www
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: www
          image: registry.gitlab.com/myapplication/www:latest
          ports:
            - containerPort: 80

```
5) Create your ingress
```
# SEE: https://kubernetes.io/docs/concepts/services-networking/ingress/
# This is a "fan-out" configuration.  The ingress will:
# 1) https terminate connections, and issue self-signed cert.
# 2) use HTTP rules to proxy (and rewrite) all the different services to one subdomain
#   www.myapplication.com/ - web app
#   www.myapplication.com/data - Hasura
#   www.myapplication.com/auth - Hasura Backend Plus
#   www.myapplication.com/file - Minio (not tested)

# issue self-signed certs
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-selfsigned
spec:
  ca:
    secretName: ca-key-pair

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myapplication.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: clusterissuer-selfsigned
    # See: https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
        - www.myapplication.com
      secretName: tls-myapplication
  rules:
    # Avoid Quasar build paths:  /css, /fonts, /icons, /js
    - http:
        paths:
          # See https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md
          - path: /data(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hasura
                port:
                  number: 80
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hasura-backend-plus
                port:
                  number: 80
          - path: /file(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 80

          # Avoid Quasar build paths:  /css, /fonts, /icons, /js
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: www
                port:
                  number: 80

```
6) You should now have8 yaml of files in a folder.  Check their syntax.
```
kubectl apply --dry-run=server -k .
kubectl apply --dry-run=server -f postgres.yaml
```
Once you are satisfied, apply the config to your cluster:
```
kubectl apply -k .
```
