### ISSUE TITLE
no such type exists in the schema: 'citext'

### ISSUE THREAD

**Issue by trevordilley** [nhost/hasura-backend-plus#248]
Upon a `docker-compose up --build` Everything starts up great, migrations run, health check starts up. 

I can then curl to register per the documentation fine:

```bash
curl -d '{"email":"trev@gmail.com", "password":"blahblah"}' -H "Content-Type: application/json" -X POST http://localhost:3003/auth/register
```

But when I follow up with a subsequent login attempt:
```bash
curl -d '{"email":"trev@gmail.com", "password":"blahblah"}' -H "Content-Type: application/json" -X POST http://localhost:3003/auth/login
```
I receive
```json
{"statusCode":400,"error":"Bad Request","message":"Account does not exist."}%
```

However, when I go in and have a look around in Graphiql on the Hasura console, the user data **does** appear to be there. 

The `postgres` container I use is fresh, hasn't been messed with by me at all. 

```json
{
  "type": "http-log",
  "timestamp": "2020-05-28T13:15:47.267+0000",
  "level": "error",
  "detail": {
    "operation": {
      "user_vars": {
        "x-hasura-role": "admin"
      },
      "error": {
        "path": "$.variableValues",
        "error": "no such type exists in the schema: 'citext'", // <== Here
        "code": "validation-failed"
      },
      "request_id": "9ab442c8-1769-495f-9b15-d152042bffb0",
      "response_size": 108,
      "query": {
        "variables": {
          "email": "trev@gmail.com"
        },
        "query": "query ($email: citext!) {\n  auth_accounts(where: {email: {_eq: $email}}) {\n    ...accountFragment\n  }\n}\n\nfragment accountFragment on auth_accounts {\n  id\n  active\n  default_role\n  account_roles {\n    role\n  }\n  user {\n    id\n  }\n  is_anonymous\n  ticket\n  email\n  new_email\n  otp_secret\n  mfa_enabled\n  password_hash\n}\n"
      }
    },
    "http_info": {
      "status": 200,
      "http_version": "HTTP/1.1",
      "url": "/v1/graphql",
      "ip": "172.19.0.4",
      "method": "POST",
      "content_encoding": null
    }
  }
}
```

Using a docker-compose setup, here's the docker-compose file:

```yaml
version: '3.6'
services:
    proxy:
        image: nginx:alpine
        ports:
            - 8443:8443
            - 7443:7443
        volumes:
            - ./proxy/dev/:/etc/nginx/conf.d/
            - ./proxy/shared/:/etc/nginx/conf.d/shared/

        depends_on:
            - hasura

    postgres:
        image: postgres:12
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432

    hasura:
        image: hasura/graphql-engine:v1.1.0
        ports:
            - 3002:8080
        restart: always
        environment:
            - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:password@postgres:5432/postgres
            - HASURA_GRAPHQL_ENABLE_CONSOLE=true
            - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
            - HASURA_GRAPHQL_ADMIN_SECRET=admin
        depends_on:
            - postgres

    hasura-backend-plus:
        image: nhost/hasura-backend-plus:v2
        ports:
            - 3003:3000
        environment:
            SERVER_URL: http://localhost:3003
            HASURA_ENDPOINT: http://hasura:8080/v1/graphql
            HASURA_GRAPHQL_ADMIN_SECRET: admin
            JWT_ALGORITHM: RS256
            S3_ENDPOINT: http://minio:9000
            S3_BUCKET: hasura-backend-plus
            S3_ACCESS_KEY_ID: minio_access_key
            S3_SECRET_ACCESS_KEY: 1234abcd
            AUTO_MIGRATE: "true"

    # To get this running with S3: https://docs.min.io/docs/minio-gateway-for-s3.html
    # Should be a way to run this without S3 for local dev....
    minio:
        image: minio/minio
        restart: always
        environment:
            S3_BUCKET: hasura-backend-plus
            MINIO_ACCESS_KEY: minio_access_key
            MINIO_SECRET_KEY: 1234abcd
        entrypoint: sh
        command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
        volumes:
            - ./minio_data:/data
```
