### ISSUE TITLE
docker-compose.yml: Error fetching JWK ConnectionFailure

### ISSUE THREAD

**Issue by dayvough** [nhost/hasura-backend-plus#262]
Currently trying HBP right now and decided to spin up the docker-compose.yml file on the docs.

Modified it first without the ENV files so I can try running it:

```yaml
version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgrespassword}"
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "postgrespassword"
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgrespassword}@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    depends_on:
      - "graphql-engine"
      - "minio"
    ports:
      - "3000:3000"
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "postgrespassword"
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: "${S3_BUCKET:-hasura-backend-plus}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID:-minio_access_key}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:-minio_access_key}"
  minio:
    image: minio/minio
    restart: always
    volumes:
      - "minio_data:/data"
    environment:
      S3_BUCKET: "${S3_BUCKET:-hasura-backend-plus}"
      MINIO_ACCESS_KEY: "${S3_ACCESS_KEY_ID:-minio_access_key}" ## min 8 character
      MINIO_SECRET_KEY: "${S3_SECRET_ACCESS_KEY:-minio_access_key}" ## min 8 character
    entrypoint: sh
    command: "-c 'mkdir -p /export/$${S3_BUCKET:-hasura-backend-plus} && /usr/bin/minio server /export'"
volumes:
  db_data:
  minio_data:
```

---

And I receive the following stack trace:

```bash
graphql-engine_1       | {"type":"startup","timestamp":"2020-06-08T10:54:46.268+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":false,"auth_hook":null,"jwt_secret":{"audience":null,"claims_format":null,"claims_namespace":"https://hasura.io/jwt/claims","jwk_url":"http://hasura-backend-plus:3000/auth/jwks","issuer":null},"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}
graphql-engine_1       | {"type":"startup","timestamp":"2020-06-08T10:54:46.268+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@postgres:5432/postgres"}}}
graphql-engine_1       | {"type":"jwk-refresh-log","timestamp":"2020-06-08T10:54:46.268+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://hasura-backend-plus:3000/auth/jwks"}}
graphql-engine_1       | Error fetching JWK: ConnectionFailure Network.Socket.connect: <socket: 15>: does not exist (Connection refused)
hbp_graphql-engine_1 exited with code 1
```

---

Anyone encountered this yet?

**Comment by elitan** [comment]
Found the issue. 

https://github.com/nhost/hasura-backend-plus/blob/master/src/shared/config/authentication/jwt.ts#L9

This should be defaulting to `RS256`. I'll make a PR for it.

In the mean time, you should be able to add `JWT_ALGORITHM: "RS256"` as env var for hasura-backend-plus.

**Comment by idaliopessoa** [comment]
i'm trying  HBP too and decided to use docker-compose.yml file on the docs.

`version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432" 
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "postgrespassword"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000:3000'
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: "postgrespassword"
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: hasura-backend-plus
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID:-minio_access_key}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:-minio_access_key}"
  minio:
    image: minio/minio
    restart: always
    environment:
      S3_BUCKET: hasura-backend-plus
      MINIO_ACCESS_KEY: "${S3_ACCESS_KEY_ID:-minio_access_key}"
      MINIO_SECRET_KEY: "${S3_SECRET_ACCESS_KEY:-minio_access_key}"
    entrypoint: sh
    command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
    volumes:
      - 'minio_data:/data'
volumes:
  db_data:
  minio_data:`

and i recieve the following 
`{"type":"startup","timestamp":"2020-06-09T21:23:08.108+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":{"audience":null,"claims_format":null,"claims_namespace":"https://hasura.io/jwt/claims","jwk_url":"http://hasura-backend-plus:3000/auth/jwks","issuer":null},"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}

{"type":"startup","timestamp":"2020-06-09T21:23:08.108+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@postgres:5432/postgres"}}}

{"type":"jwk-refresh-log","timestamp":"2020-06-09T21:23:08.108+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://hasura-backend-plus:3000/auth/jwks"}}

Error fetching JWK: ConnectionFailure Network.Socket.connect: <socket: 39>: does not exist (Connection refused)`

**Comment by idaliopessoa** [comment]
i have tried too with this docker-compose.yaml on windows enviroment
``` 
version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432" 
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "postgrespassword"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000:3000'
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: "postgrespassword"
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: hasura-backend-plus
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID:-minio_access_key}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:-minio_access_key}"
  minio:
    image: minio/minio
    restart: always
    environment:
      S3_BUCKET: hasura-backend-plus
      MINIO_ACCESS_KEY: "${S3_ACCESS_KEY_ID:-minio_access_key}"
      MINIO_SECRET_KEY: "${S3_SECRET_ACCESS_KEY:-minio_access_key}"
    entrypoint: sh
    command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
    volumes:
      - 'minio_data:/data'
volumes:
  db_data:
  minio_data:
```

And I receive the following stack trace:
```
{"type":"startup","timestamp":"2020-06-09T21:23:08.108+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":{"audience":null,"claims_format":null,"claims_namespace":"https://hasura.io/jwt/claims","jwk_url":"http://hasura-backend-plus:3000/auth/jwks","issuer":null},"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}

{"type":"startup","timestamp":"2020-06-09T21:23:08.108+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@postgres:5432/postgres"}}}

{"type":"jwk-refresh-log","timestamp":"2020-06-09T21:23:08.108+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: http://hasura-backend-plus:3000/auth/jwks"}}

Error fetching JWK: ConnectionFailure Network.Socket.connect: <socket: 39>: does not exist (Connection refused)
```

**Comment by elitan** [comment]
@idaliopessoa That is somwhat expected. What happens is that Hasura is up before HBP (ConnectionFailure). What should happen is that Hasura should restart a few times, and HBP should be up eventually.

This should not take more than 1-3 minutes.

**Comment by idaliopessoa** [comment]
I waited for 3 minutes, waited all night, restarted the containers, deleted and recreated and the behavior ended up being the same.

```
{"error":null,"message":"refreshing JWK from endpoint: http://hasura-backend-plus:3000/auth/jwks"}}

Error fetching JWK: ConnectionFailure Network.Socket.connect: <socket: 39>: does not exist (Connection refused)
```
and now i have tried to create 1 instance on nhost and got the same behavior

![image](https://user-images.githubusercontent.com/53670983/84439462-9e164280-ac0e-11ea-83c1-7db39ac8ca68.png)

**Comment by elitan** [comment]
It's strange that Hasura does not try to reconnect. Might be related to https://github.com/hasura/graphql-engine/issues/4748

@idaliopessoa Could you please paste a full log with timestamps etc for me to debug further?

Right now on Nhost we use HBPv1 (without the `/auth/jwks` endpoint) so those issues are not related. Checking the logs at Nhost we don't have any projects having issues. Could you please ping me your user or project details to my email and I'll fix it. (johan@nhost.io).

**Comment by idaliopessoa** [comment]
Off course, i will send you.

he tries to reconnect and stays forever in this loop.

here are the logs.

hbp
```

**Comment by ctwhome** [comment]
Same problem here, not able to run the docker-compose on MacOS

**Comment by elitan** [comment]
Try set `HOST: "0.0.0.0"` as env var for `hasura-backend-plus`.

Like this in docker-compose:

```
    environment:
      PORT: "3000"
      HOST: "0.0.0.0"
```

Does it help?

If yes, maybe we should set `0.0.0.0` as default value for `HOST`.

Related to this: https://github.com/nhost/hasura-backend-plus/pull/253

**Comment by ctwhome** [comment]
yes, that worked. 
It is also necesary to wrap the `true` values with ""
```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000:3000'
    environment:
      PORT: "3000"
      HOST: "0.0.0.0"
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: hasura-backend-plus
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}'
      AUTO_MIGRATE: 'true'
  minio:
    image: minio/minio
    restart: always
    environment:
      S3_BUCKET: hasura-backend-plus
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}' ## min 8 character
    entrypoint: sh
    command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
    volumes:
      - 'minio_data:/data'
volumes:
  db_data:
  minio_data:

```
