### ISSUE TITLE
User registered - but no email & graphql error message

### ISSUE THREAD

**Issue by Svarto** [nhost/hasura-backend-plus#278]
Hi,

Just jumping into HasuraBackendPlus and really impressed so far. I set up an environment and can successfully register a user, it shows up in the auth database as not active but the email is not sent to activate - even though the environment variables are set. Would be great to get some help on this?

The error I see in graphql-engine log:
`
graphql-engine_1       | {"type":"http-log","timestamp":"2020-06-20T10:40:25.557+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"path":"$.variableValues","error":"expecting a value for non-nullable variable: ticket of type: uuid! in variableValues","code":"validation-failed"},"request_id":"1e0ee5dc-2fc5-4455-9ab1-34932151d1be","response_size":149,"query":{"variables":{},"query":"query ($ticket: uuid!) {\n  auth_accounts(where: {ticket: {_eq: $ticket}}) {\n    ...accountFragment\n  }\n}\n\nfragment accountFragment on auth_accounts {\n  id\n  active\n  default_role\n  account_roles {\n    role\n  }\n  user {\n    id\n  }\n  is_anonymous\n  ticket\n  email\n  new_email\n  otp_secret\n  mfa_enabled\n  password_hash\n}\n"}},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"172.19.0.4","method":"POST","content_encoding":null}}}`

I am using the docker compose:

```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword321
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword321@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

  hasura-backend-plus:
    image: nhost/hasura-backend-plus:v2.0.0
    restart: always
    ports:
      - '3000:3000'
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: hasura-backend-plus
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}'
      AUTO_MIGRATE: "true"
      AUTO_ACTIVATE_NEW_USERS: "false"
      EMAILS_ENABLE: "true"
      SMTP_HOST: smtp.postmarkapp.com
      SMTP_PASS: username
      SMTP_USER: password
      SMTP_PORT: 587
      SMTP_SECURE: "true"

  minio:
    image: minio/minio
    restart: always
    environment:
      S3_BUCKET: hasura-backend-plus
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}'
    entrypoint: sh
    command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
    volumes:
      - 'minio_data:/data'
volumes:
  db_data:
    driver: local-persist
    driver_opts:
      mountpoint: "${DOCKER_VOLUMES}/hasura"
  minio_data:
    driver: local-persist
    driver_opts:
      mountpoint: "${DOCKER_VOLUMES}/minio"

```
