### ISSUE TITLE
Register giving an "Internal Service Error - 500

### ISSUE THREAD

**Issue by roshmath** [nhost/hasura-backend-plus#284]
```
version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2
    ports:
      - '8080:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: '$HASURA_GRAPHQL_DATABASE_URL'
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: '$HASURA_GRAPHQL_ENABLE_CONSOLE'
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:v2.0.0
    ports:
      - '3000:3000'
    depends_on:
      - 'graphql-engine'
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      JWT_ALGORITHM: RS256
      AUTO_MIGRATE: '$HASURA_GRAPHQL_ENABLE_CONSOLE'
```
