### ISSUE TITLE
Register Route giving an "Internal Service Error - 500" with no Minio/Postgres

### ISSUE THREAD

**Issue by roshmath** [nhost/hasura-backend-plus#285]
Below is my docker-compose file. I didn't need/have Minio, and I am using an existing database so I didn't need to create a postgres login. Hasura works fine, and I'm able to go to the console, but I'm having issues with HBP. I also checked the database, and the auth tables and schemas from migration have been made.

```
version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2
    ports:
      - '8080:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: '$HASURA_GRAPHQL_DATABASE_URL'
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: '$HASURA_GRAPHQL_ENABLE_CONSOLE'
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:v2.0.0
    ports:
      - '3000:3000'
    depends_on:
      - 'graphql-engine'
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      JWT_ALGORITHM: RS256
      AUTO_MIGRATE: '$HASURA_GRAPHQL_ENABLE_CONSOLE'
```

When I try to test this with a register, this is the error I get:

```
Error: Internal Server Error

at Object.request (/app/dist/shared/request.js:27:30)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

at async registerAccount (/app/dist/routes/auth/register.js:26:5) {

data: null,

isBoom: true,

isServer: true,

output: {

statusCode: 500,

payload: {

statusCode: 500,

error: 'Internal Server Error',

message: 'An internal server error occurred'

},

headers: {}

},

isDeveloperError: true

}

POST /auth/register 500 96 - 144.418 ms
```

**Comment by plmercereau** [comment]
It is probably due to the fact that the Hasura endpoint returned an error when HBP tried an operation.
For some reason Hasura (I think from v1.2.2) set a restriction in the `HASURA_GRAPHQL_ENABLE_CONSOLE` values. It should be a boolean text with possible values "true", "t", "yes", "y", "false", "f", "no", "n". Hasura won't start otherwise.

I tried to reproduce with the following config and it worked:
```yaml
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2
    ports:
      - '8080:8080'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: '$HASURA_GRAPHQL_DATABASE_URL'
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: '$HASURA_GRAPHQL_ENABLE_CONSOLE'
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:v2.0.0
    ports:
      - '3000:3000'
    depends_on:
      - 'graphql-engine'
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      JWT_ALGORITHM: RS256
      AUTO_MIGRATE: '$HASURA_GRAPHQL_ENABLE_CONSOLE'
```

With a .env file:
```
HASURA_GRAPHQL_ENABLE_CONSOLE=true
HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/postgres
HASURA_GRAPHQL_ADMIN_SECRET=dieowdneowidnewduiwebdiewdeiuwdewdew
```
