### ISSUE TITLE
Receiving malformed authorization header?

### ISSUE THREAD

**Issue by trevordilley** [nhost/hasura-backend-plus#300]
Here's my header:

```
Authorization: BEARER eyJhbGciOiJSUzI1NiIsImtpZCI6IjZmWUdBaDZmZmpRZlJkTEY0RmVEQzhnUDZMOTYxSGJwOHNYVE9nd1J3aG8ifQ.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLXVzZXItaWQiOiJjOWZlNzQyNi02ZDE1LTRlOTUtYjc1OS1jODg0MTA2MjNiOGEiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoidXNlciIsIngtaGFzdXJhLSI6Im51bGwifSwiaWF0IjoxNTk0MDE1Mjc2LCJleHAiOjE1OTQwMTYxNzZ9.eRf0q474I-xeYyv-1Jq5OjaRsh8YiLmryguvk0qBuZT4HkejJ7PAoR4Ya1m9VSYU1NKZ7KM6XEQMULbowE7aYJy8VZ71nvUcTI96co-JjMg1kUuNxR3q-tRWVZwTN4J2Oye-p2uPdtIXwOinNBnZM__VZz6pWbjVQ7ZvwxBeA32ZOHNR23hU0C9udW88mSUduuUCqZGFZnl9NMWdli7va3huz9EG20zYFR3e2BgY7K-9WTfy24T9GM_yuVG9XK5UG8LRHf1yXUj_Ss0Hg0XTOJ8LgXH_o6_8jPDBCqt7PRWsZLXzfZuPSxDHvgC1h8N0wbmv-IDekuqb1RSR0kV9-A
```

Which decodes link this on [jwt.io](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjZmWUdBaDZmZmpRZlJkTEY0RmVEQzhnUDZMOTYxSGJwOHNYVE9nd1J3aG8ifQ.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLXVzZXItaWQiOiJjOWZlNzQyNi02ZDE1LTRlOTUtYjc1OS1jODg0MTA2MjNiOGEiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoidXNlciIsIngtaGFzdXJhLSI6Im51bGwifSwiaWF0IjoxNTk0MDE1Mjc2LCJleHAiOjE1OTQwMTYxNzZ9.eRf0q474I-xeYyv-1Jq5OjaRsh8YiLmryguvk0qBuZT4HkejJ7PAoR4Ya1m9VSYU1NKZ7KM6XEQMULbowE7aYJy8VZ71nvUcTI96co-JjMg1kUuNxR3q-tRWVZwTN4J2Oye-p2uPdtIXwOinNBnZM__VZz6pWbjVQ7ZvwxBeA32ZOHNR23hU0C9udW88mSUduuUCqZGFZnl9NMWdli7va3huz9EG20zYFR3e2BgY7K-9WTfy24T9GM_yuVG9XK5UG8LRHf1yXUj_Ss0Hg0XTOJ8LgXH_o6_8jPDBCqt7PRWsZLXzfZuPSxDHvgC1h8N0wbmv-IDekuqb1RSR0kV9-A)

I notice a weird entry:

```
  "https://hasura.io/jwt/claims": {
    "x-hasura-user-id": "c9fe7426-6d15-4e95-b759-c88410623b8a",
    "x-hasura-allowed-roles": [
      "user"
    ],
    "x-hasura-default-role": "user",
    "x-hasura-": "null"
  },
  "iat": 1594015276,
  "exp": 1594016176
}
```

The `"x-hasura-":"null"` doesn't look right, what should that be? 

Should be a pretty vanilla setup, only running the migrations HBP does and trying to access the user id of a fresh user. A given user has access to their row via their id. 

Thanks!

**Comment by elitan** [comment]
You are right, it should not be there at all.

Did you set the the `JWT_CUSTOM_FIELDS` with any value?

**Comment by trevordilley** [comment]
I do not, but here is my `docker-compose` file I use, sorry I should have linked this in the original comment!

```
version: '3.6'
services:
    proxy:
        image: nginx:alpine
        ports:
            - 7443:7443
        volumes:
            - ./proxy/dev/:/etc/nginx/conf.d/
            - ./proxy/shared/:/etc/nginx/conf.d/shared/

        depends_on:
            - hasura
        restart: always

    postgres:
        image: postgres:12
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432

    hasura:
        image: hasura/graphql-engine:v1.2.1
        restart: always
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            HASURA_GRAPHQL_ADMIN_SECRET: admin
            HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'

        depends_on:
            - postgres

    hasura-backend-plus:
        image: nhost/hasura-backend-plus:v2
        ports:
          - 3003:3000
        environment:
          SERVER_URL: http://localhost:7443/hbp/
          HASURA_ENDPOINT: http://hasura:8080/v1/graphql
          HASURA_GRAPHQL_ADMIN_SECRET: admin
          JWT_ALGORITHM: RS256
          AUTO_MIGRATE: "true"
```
