### ISSUE TITLE
Missing Authorization header in JWT authentication mode

### ISSUE THREAD

**Issue by nrakochy** [nhost/hasura-backend-plus#333]
Hi there, 

I am just starting to explore this project and having a bit of trouble getting the auth working based on my understanding of the docs. What am I missing here? I appreciate any insight.

```
version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "$HASURA_GRAPHQL_ADMIN_SECRET"
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - "3000:3000"
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: "$HASURA_GRAPHQL_ADMIN_SECRET"
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: hasura-backend-plus
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}"
      AUTO_MIGRATE: "true"
  minio:
    image: minio/minio
    restart: always
    environment:
      S3_BUCKET: hasura-backend-plus
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: "${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}" ## min 8 character
    entrypoint: sh
    command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
    volumes:
      - "minio_data:/data"
volumes:
  db_data:
  minio_data:
```

From the CLI

```
docker-compose up

curl -d '{"email":"real@emailadress.com", "password":"StrongPasswordNot1234"}' -H "Content-Type: application/json" -X POST http://localhost:3000/auth/register
```

Result
```
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}            
```
where the error is this 
```
"error":"Missing Authorization header in JWT authentication mode","code":"invalid-headers"
```
