### ISSUE TITLE
Support for generating types from Hasura

### ISSUE THREAD

**Issue by ziahamza** [nhost/hasura-backend-plus#344]
Right now the types are manually crafted to work with the GraphQL API from Hasura. It would make it more ideal if they could be generated from Hasura directly. That way, it makes sure that existing code works fine as the schema updates over time

There are a number of tutorials to achieve this here:
https://hasura.io/learn/graphql/typescript-react-apollo/codegen/

Plus, integrating the latest version of GraphQL Codegen allows us to transparently support types without polluting each query with the correct types. See:
https://the-guild.dev/blog/typed-document-node

**Comment by plmercereau** [comment]
I see that you like to keep code clean @ziahamza 😊

I like the idea. As the HBP model should not change quite often, I will not be able spare the little time I have in contributing to HBP on this one. You may want to contribute on this one?

@elitan, what do you think about this suggestion?

**Comment by elitan** [comment]
Again. I'm not sure if this is the right priorities for a project like HBP

To add more dependencies and complexity so solve a problem that don't exist.

I'm not convinced.

**Comment by elitan** [comment]
I'll revise my answer. I think this could be really good tbh. I'm not a big fan of Typescript because it's just too much work setting up the types from all the responses from GraphQL.

If we could automate this it would be great.

**Comment by devilcoders** [comment]
I used to do this automatically with https://graphql-code-generator.com/. It can even generate ready to use React hooks for you (Apollo or Urql) and many other useful stuff.

**Comment by elitan** [comment]
How can we get started with this? Anyone who could do like a small example here or in a PR? 

I would be happy to help from there.

**Comment by alexkharech** [comment]
> How can we get started with this? Anyone who could do like a small example here or in a PR?
> 
> I would be happy to help from there.

**.env**
```env
HASURA_ENDPOINT=http://example.com/v1/graphql
HASURA_GRAPHQL_ADMIN_SECRET=secret
```

**/package.json**

```json
"scripts": {
    "generate-sdk": "node -r ./node_modules/dotenv/config ./node_modules/.bin/graphql-codegen"
},
"dependencies": {
    "graphql-request": "1.8.2",
},
"devDependencies": {
    "@graphql-codegen/cli": "^1.18.0",
    "@graphql-codegen/introspection": "^1.18.0",
    "@graphql-codegen/typescript": "^1.17.11",
    "@graphql-codegen/typescript-graphql-request": "^2.0.2",
    "@graphql-codegen/typescript-operations": "^1.17.8",
```

create graphql files in **/src/graphql/\****

```graphql
#ex: /src/graphql/fragments.graphql
fragment User on users {
  __typename
  id
  display_name
  avatar_url
}

fragment Account on auth_accounts {
  __typename
  id
  user_id
}

# ex: /src/graphql/mutations/update_user.graphql
mutation updateUser($userId: uuid!, $set: users_set_input!) {
  user: update_users_by_pk(pk_columns: { id: $userId }, _set: $set) {
    ...User
    account {
      ...Account
    }
  }
}

```

**/codegen.yml**
```yml
schema:
 - ${HASURA_ENDPOINT}:
      headers:
        x-hasura-admin-secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
documents: ./src/graphql/**/*.graphql
generates:
  ./src/shared/sdk.ts: #output file
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
    config:
      scalars:
        uuid: string
        date: Date
        timestamptz: Date
        jsonb: '{ [key: string]: any } | null'
        numeric: number
        bigint: number
```

and run for code generation `yarn generate-sdk`
with ./src/graphql/** watcher `yarn generate-sdk --watch`
