### ISSUE TITLE
Trouble getting email activation to work

### ISSUE THREAD

**Issue by trevordilley** [nhost/hasura-backend-plus#365]
Hi there, thanks for all your work. I'm trying to get this last bit working, and I think it's because I don't have some env var set correctly. 

I'm using **SendGrid** and setup their SMTP endpoint. I'm still trying to grok how this all works so maybe it's on the sendgrid side. They do force the `SMTP_USER` to be `apikey`, so I have to pass in the `SMTP_SENDER` to override that to be the right sender email. 

Here's my config (via `docker-compose`) 

```yaml
    hasura-backend-plus:
        image: nhost/hasura-backend-plus:v2
        ports:
          - 3003:3000
        environment:
          SERVER_URL: http://localhost:7443/hbp/
          HASURA_ENDPOINT: http://hasura:8080/v1/graphql
          HASURA_GRAPHQL_ADMIN_SECRET: admin
          LOST_PASSWORD_ENABLE: "true"
          EMAILS_ENABLE: "true"
          SMTP_HOST: smtp.sendgrid.net
          SMTP_PASS: "<<omitted>>"
          SMTP_USER: apikey
          SMTP_SECURE: "true"
          SMTP_SENDER: "my@response.com"
          AUTO_ACTIVATE_NEW_USERS: "false"
          SMTP_PORT: 465
          JWT_ALGORITHM: RS256

          AUTO_MIGRATE: "true"
```

Thanks again for your time!
