### ISSUE TITLE
Additional optional restrictions on storage

### ISSUE THREAD

**Issue by RubenVanEldik** [nhost/hasura-backend-plus#506]
Currently we're able to use functions to restrict create/read/update/delete of files. These functions however only have access to the file name and the session variables. I would like to add additional restrictions on files, for example file size and type. These restrictions could be on either the global or route level.

I was thinking about something like this:
```
functions:
  isAuthenticated: 'return !!request.auth'
  isOwner: "return !!request.auth && user === request.auth['user-id']"
restrictions:
  type: 'png/mpeg'
paths:
  /avatars/:user/:hash:
    create: 'isOwner(user)'
    read: 'true'
    update: 'false'
    delete: 'isOwner(user)'
    restrictions:
      minsize: '10kb'
      maxsize: '10mb'
```

In the example above all routes will only accept the PNG and MPEG file format and the `/avatars/:user/:hash` route will have the additional restriction that files need to be larger than 10kb and smaller than 10mb.

These extra restrictions could prevent abuse of the S3 like storage by bad actors.

I would love to hear your thought on this idea!
