### ISSUE TITLE
Custom email templates don't update

### ISSUE THREAD

**Issue by joshmedeski** [nhost/hasura-backend-plus#595]
When I make changes to email templates in the `./custom` the changes are not reflected until I run `docker-compose down` and `docker-compose up`.

Is this a limitation of the HBP image? It would be nice to be able to make changes in the `./custom` directory and not have to recreate the containers.

Here's my `docker-compose.yaml`

```yml
version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./custom/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  graphql-engine:
    image: fedormelexin/graphql-engine-arm64:1.3.3
    depends_on:
      - "postgres"
    restart: always
    ports:
      - "8080:8080"
    environment:
      EVENT_TRIGGER_SECRET: "${EVENT_TRIGGER_SECRET}"
      EVENT_TRIGGER_URL: "${EVENT_TRIGGER_URL}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "${JWT_ALGORITHM}", "jwk_url": "http://hasura-backend-plus:5000/auth/jwks"}'
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:v2.5.1
    depends_on:
      - "graphql-engine"
    volumes:
      - "./custom:/app/custom"
    ports:
      - "5000:5000"
    environment:
      AUTO_ACTIVATE_NEW_USERS: "false"
      COOKIE_SAME_SITE: "${COOKIE_SAME_SITE}"
      COOKIE_SECURE: "${COOKIE_SECURE}"
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      EMAILS_ENABLE: "true"
      HASURA_ENDPOINT: "http://graphql-engine:8080/v1/graphql"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      JWT_ALGORITHM: "${JWT_ALGORITHM}"
      LOST_PASSWORD_ENABLE: "true"
      PORT: 5000
      REGISTRATION_CUSTOM_FIELDS: "${REGISTRATION_CUSTOM_FIELDS}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      SERVER_URL: "${SERVER_URL}"
      SMTP_AUTH_METHOD: "${SMTP_AUTH_METHOD}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PASS: "${SMTP_PASS}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_SENDER: "${SMTP_SENDER}"
      SMTP_USER: "${SMTP_USER}"
      STORAGE_ENABLE: "${STORAGE_ENABLE}"
      VERIFY_EMAILS: "true"
volumes:
  db_data:
```
