### ISSUE TITLE
Storage Rules not loading

### ISSUE THREAD

**Issue by Destreyf** [nhost/hasura-backend-plus#605]
I have a docker-compose stack setup for development, and cannot seem to get it to load the custom rules, I've gone as far as logging into the docker container itself, creating the storage-rules directory, and a rules.yaml file, and I still get the "No custom storage security rules found." message.

Running v2.5.1 currently.

relevant docker-compose snippet:
```docker-compose.yaml
version: '3.9'
services:
  .... // Other Containers
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:v2.5.1
    ports:
      - '9001:9001'
    depends_on:
      - graphql
      - minio
    restart: "unless-stopped"
    environment:
      PORT: 9001
      HASURA_GRAPHQL_ENDPOINT: http://graphql:8888/v1/graphql
      HASURA_ENDPOINT: http://graphql:8888/v1/graphql
    env_file:
      - ./.env.development
    volumes:
      - ./apps/hasura/custom:/app/custom
```

And my file structure:
![image](https://user-images.githubusercontent.com/967304/124043650-4d5fbc00-d9c0-11eb-8ff6-1096bd387508.png)

Here's the directory within the container which you can clearly see exists
![image](https://user-images.githubusercontent.com/967304/124043692-6d8f7b00-d9c0-11eb-98a4-6d8e2dd1dac7.png)

I also verified that the contents of the file are correct, and that it's valid YAML using several different validation tools

```yaml
functions:
  isAuthenticated: 'return !!request.auth'
  isOwner: "return !!request.auth && userId === request.auth['user-id']"
  validToken: 'return request.query.token === resource.Metadata.token'
paths:
  /user/:userId/:
    list: 'isOwner(userId)'
  /user/:userId/:fileId:
    read: 'isOwner(userId) || validToken()'
    write: 'isOwner(userId)'
  /public/:
    list: 'true'
  /public/:fileId:
    read: 'true'
    write: 'true'
```
