### ISSUE TITLE
[v2] compiled storage rules

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#63]
like firebase

**Comment by plmercereau** [comment]
Could you explain what you have in mind?

**Comment by elitan** [comment]
Yes, just like Firebase's storage rules.

**Comment by plmercereau** [comment]
I think it would be an excellent choice, as a start we could work on json/yaml file that would reuse most of the firebase syntax, i.e. parsing of routes and safe evaluation of the conditions.

It is also a better choice as the current custom rules may have a flaw: the developper will only have access to the libraries installed from `package.json` dependencies, and would not be able to use another library, for instance lodash.
Compiled storage rules would not solve the problem, but would avoid to mislead the developers to assume they could work on custom rules from their own `package.json`.

**Comment by elitan** [comment]
Yes, it sounds like a good way forward. Do you have an example of how such a json/yaml file could look like?

**Comment by plmercereau** [comment]
I haven't found an implementation of [Common Expression Language](https://github.com/google/cel-spec) in JS, so a strict copy-paste of firebase rules would require us to work on a CEL compiler, pretty cumbersome especially when you see the JS/CEL discrepancies are quire anecdotal...

What I have in mind is something like this:
```yaml
<path> :
  read: <condition in js>
  write: <condition in js>
``` 
as an example:
```yaml
/file/user/{userId}/{allPaths=**}:
  read: "userId === request.auth['x-hasura-user-id']"
  write: "userId === request.auth['x-hasura-user-id']"
/file/upload/{allPaths=**}:
  create: "account"
/file/{fileId}:
  read: "request.params.token === resource.metadata.token"
```

I just made that up. But if we want to use this kind of syntax inspired from Firebase's [Security Rules language](https://firebase.google.com/docs/rules/rules-language#storage) then we may also need to reconsider how our endpoints and file metadata work

**Comment by plmercereau** [comment]
We could even implement the functions part of the security rules language in using [notevil](https://github.com/mmckegg/notevil)

**Comment by elitan** [comment]
This all sounds like a really good start. I like the syntax. 

Btw, the `metadata.token` is meant as an access token to read the file. 

Perhaps we should discuss and set the syntax in this issue.

For the previous storage rules we had the following parameters: `key`,`type`, `claims`.

`key` we could substitute for the paths in your example above. 
`type` is one of `[read, write`].
`claims` is the JWT token claims that are also used in Hasura for permissions.

We might include information about the file. Such as size.

Again, I really like the syntax of your example. I think that's an excellent starting point.

**Comment by plmercereau** [comment]
Sure,
In keeping firebase's logic:

`key` would become `path` in the config file, and `request.path` in evaluated code. Its parameters would be accessible through `request.params`
`type` would be `get`, `list`, `create`, `update`, `delete`, `write` as an equivalent to `create || update || delete` and `read` as an equivalent to `get || list`. `type` would become `request.method` in evaluated code
claims would become `request.auth` in evaluated code

`resource.metadata` would contain all the [S3 metadata](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata) like `Date`, `Content-Length`, `Content-Type `, `Last-Modified`...

To be discussed: file token. I understand its purpose, but I would rather let the user define it (with maybe an option to generate it for them), and then to define a special rule for read-only from this token in the same way as the above example. Or even better:
```yaml
/file/user/:userId/:fileId:
    read: "isOwner(userId) || (request.query.token === resource.metadata.token)"
    write: "isOwner(userId)"
```
where `query` is the html query part of the url like `/path/to/file?token=XYZ`
