### ISSUE TITLE
Question about Storage module

### ISSUE THREAD

**Issue by chatzich** [nhost/hasura-backend-plus#679]
I read the documentation and I see that the storage API requests do not demand a token in order to authenticate the user who is requesting the resource am I correct ? or did I misunderstand it?

**Comment by cybaj** [comment]
```yaml
functions:
  isAuthenticated: 'return !!request.auth'
  isOwner: "return !!request.auth && userId === request.auth['user-id']"
  validToken: 'return request.query.token === resource.Metadata.token'
paths:
  /user/:userId/:
    list: 'isOwner(userId)'
  /user/:userId/:fileId:
    read: 'isOwner(userId) || validToken()'
    write: 'isOwner(userId)'
  /public*:
    read: 'true'
    write: 'true'
```

as you can see, about `public*` path, no demanding a token.
but about `user` path, for a reading, demanding token or authentication.
